language: node_js
sudo: false
node_js:
  - '4.2'
branches:
  only:
    - master
    - develop
env:
  global:
    - GIT_COMMITTER_NAME=travis-ci
    - GIT_COMMITTER_EMAIL=inc@2inc.org
    - GIT_AUTHOR_NAME=travis-ci
    - GIT_AUTHOR_EMAIL=inc@2inc.org
    - secure: "R4JNdNzLsscN+8bY3/sVG8idY/7m/DQhHceHSebQOSu1fgcM3POlU6tAIQ6p0xoqA+WqMoVdnYpkN4T7Y45WuRoVDOs60kud4bUWwbIzveCo3pSBcsHSNBoQrGqClVdsoL9PU4054/tGG+2HGgIM14gr9h0JL0Q+qCAABVX+41Bhf8YPsP99a0rAj9UwFlGrUMvLcwE/wb/6rprYnPRJYbzjBqxte+8srGS/iOCUKq3NZ3cnqsfm65S2YESdWzpwl0wQ6gU5Ojq1Np0+zfk4uvlffzhT8egE7IZaNEr5pG7O0hAM6/zCTkn543xd+EkmScV6KU7+EwpWgTg/Hgy76dl3GB/GukcadGOwZNxTJr0LdGGBMltwppRFXJgilCvJ5u7a3c9MdAjE2HDwAGm4XQ8ueFy8oY6VWa2AQK9YMqmlJcWgHXsDpmdJE1Up3Qt1sfNgHc7b5owsCk63cqOTExrjcWJtmQEbTOkjCODF7itQhLy1CcA59KyNrppX1OFLgtVso0FlN1dHQrD/aM5oys/2ZTEwxTMAPkqL/E3+zVjlMUk9CB6Fg237S0xY1MCCuW2DXC2zuVFaHNElPgypoUIs9xMhU+DDKHBFcdJuXTrWlQxml90+hrPvPYtfAKngZae5AsPNdgVdIF0ZeliYesLM8eTckki2CquP4rTUBF8="
before_script:
  - git clone -b master --quiet https://github.com/getbasis/getbasis.github.io.git gh-pages
script:
  - cd gh-pages
  - ls | xargs rm -rf
  - rm -rf .gitignore .travis.yml
  - cd ../
  - npm run deploy
after_success:
  - bash ./bin/deploy.sh
